

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AddressBook.Models.Entity
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class AdresDefteriEntities : DbContext
{
    public AdresDefteriEntities()
        : base("name=AdresDefteriEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Registration> Registration { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<User> User { get; set; }

}

}

